from __future__ import annotations

from pathlib import Path

import pandas as pd

from backend.core.config import get_predictions_path


# Hold the prepared prediction table used by the website/backend route lookup.
class PredictionArtifacts:
    def __init__(self, predictions: pd.DataFrame):
        self.predictions = predictions


# Load the prepared predictions CSV generated by src.predict.
def load_prediction_artifacts(
    predictions_path: str | Path | None = None,
    data_key: str = "2014",
) -> PredictionArtifacts:
    if predictions_path is None:
        predictions_path = get_predictions_path(data_key)
    predictions = pd.read_csv(predictions_path, parse_dates=["datetime"])
    predictions = predictions.sort_values(["datetime", "scats_number", "location"]).reset_index(drop=True)
    return PredictionArtifacts(predictions=predictions)
